export const MENSAGENS_DE_ERRO = {
  nomeVazio: 'O campo "Nome" não pode ser vazio',
  municipioVazio: 'O campo "Municipio" não pode ser vazio',
  emailVazio: 'O campo "E-mail" não pode ser vazio',
  cpfVazio: 'O campo "CPF" não pode ser vazio',
  cargoVazio: 'O campo "Cargo" não pode ser vazio',
  telefoneVazio: 'O campo "Telefone" não pode ser vazio',
  equipeVazio: 'O campo "Equipe" não pode ser vazio',
  autorizacoesVazias: 'Selecione ao menos uma autorização',
};

export const CARGOS = [
  { id: 'Coordenação de Equipe', descricao: 'Coordenação de Equipe' },
  { id: 'Coordenação APS', descricao: 'Coordenação APS' },
  { id: 'Impulser', descricao: 'Impulser' },
  { id: 'Médica (o)', descricao: 'Médica (o)' },
  { id: 'Técnica (o) de Enfermagem', descricao: 'Técnica (o) de Enfermagem' },
  { id: 'Enfermeira (o)', descricao: 'Enfermeira (o)' },
  { id: 'Gestão APS', descricao: 'Gestão APS' },
  { id: 'Gestor(a) de RAPS', descricao: 'Gestor(a) de RAPS' },
  { id: 'Apoiador(a) Institucional ou Referência Técnica', descricao: 'Apoiador(a) Institucional ou Referência Técnica' },
  { id: 'Gerente', descricao: 'Gerente' },
  { id: 'Diretor(a)', descricao: 'Diretor(a)' },
  { id: 'Secretário Municipal de Saúde.', descricao: 'Secretário Municipal de Saúde.' },
  { id: 'Supervisor(a)', descricao: 'Supervisor(a)' },
  { id: 'Especialista', descricao: 'Especialista' },
  { id: 'Coordenador(a)', descricao: 'Coordenador(a)' },
  { id: 'Assessor(a)', descricao: 'Assessor(a)' },
  { id: 'Chefe de Serviço', descricao: 'Chefe de Serviço' },
  { id: 'Gestor(a) de Serviço', descricao: 'Gestor(a) de Serviço' },
  { id: 'Profissional Administrativo', descricao: 'Profissional Administrativo' },
  { id: 'Chefe de Setor', descricao: 'Chefe de Setor' },
];
