name: "End-to-End and visual Testing"

on:
  push:

jobs:
  end-to-end-testing-playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Wait for Vercel Deployment
        run: |
          GIT_SHA=$(git rev-parse HEAD)
          echo "Looking for deployment with commit SHA: $GIT_SHA"
          
          for i in {1..30}; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&teamId=${{ secrets.VERCEL_TEAM_ID }}")

            DEPLOY_URL=$(echo "$response" | jq -r --arg GIT_SHA "$GIT_SHA" '
              .deployments[] | select(.meta.githubCommitSha == $GIT_SHA) | .url')

            if [[ -n "$DEPLOY_URL" && "$DEPLOY_URL" != "null" ]]; then
              echo "::notice::Found deployment: $DEPLOY_URL"
              echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
              break
            fi
            
            echo "Deployment not found yet... retrying in 10s"
            sleep 10
          done

          if [[ -z "$DEPLOY_URL" || "$DEPLOY_URL" == "null" ]]; then
            echo "::error::Deployment not found for commit SHA: $GIT_SHA"
            exit 1
          fi
        shell: bash

      - name: Run Playwright tests
        run: DEBUG=pw:webserver yarn playwright test
        env:
          BASE_URL: ${{ env.DEPLOY_URL }}
          ENV: development

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  chromatic:
    name: visual-regression-testing-chromatic
    needs: end-to-end-testing-playwright
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.0
      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile
      - name: Download Playwright test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          playwright: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          CHROMATIC_ARCHIVE_LOCATION: playwright-report/