name: Run Linter

on: [pull_request]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22"

            - name: Install dependencies
              run: |
                  yarn install
            - name: Run Prisma Generate
              run: yarn prisma generate
            - name: Check Prisma Client is generated for Production
              run: test -d node_modules/@prisma/client || (echo "Prisma client not generated for Production" && exit 1)
              # TODO remover execução apenas em /features no futuro
            - name: Run ESLint
              run: yarn eslint src/features --ext .ts,.tsx
