name: Unit Tests

permissions:
    contents: read

on:
    pull_request:
        branches:
            - main

jobs:
    NextJS-Tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        env:
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "23"

            - name: Install dependencies
              run: |
                  yarn install

            - name: Run Jest tests
              run: yarn test
